version: '1'
name: sit-assist
services:
  deepfake-audio-detection:
    container_name: deepfake-audio-detection
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes:
      - ./data/:/app/data
      - ./notebooks/:/app/notebooks
      - ./output/:/app/output
      - ./pyfiles/:/app/pyfiles
      - ./config/:/app/config
      - ./models/:/app/models
      - ./exp_result/:/app/exp_result
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
        - "$JUPYTER_PORT:$JUPYTER_PORT"
        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
    env_file:
     - ./.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root
    