version: '1'
name: sit-tensorflow-gpu
services:
  tensorflow-jupyter-gpu:
    container_name: tensorflow-jupyter-gpu
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    tty: true
    volumes:
      - ./data/:/app/data
      - ./notebooks/:/app/notebooks
      - ./output/:/app/output
      - ./pyfiles/:/app/pyfiles
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
        - "$JUPYTER_PORT:8888"
        - "$TENSORBOARD_PORT:6006"
    env_file:
     - ./.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root
    