version: '1'
name: sit-aasist
services:
  deepfake-audio-detection-deployment:
    container_name: deepfake-audio-detection-deployment
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./:/app/
      - ./models/:/app/models/
      - ./audio/:/app/audio/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
        - "$JUPYTER_PORT:$JUPYTER_PORT"
        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
        - "$GRADIO_SERVER_PORT:$GRADIO_SERVER_PORT"
    env_file:
     - ./.env
    entrypoint: python GUI.py